"""The generated contract: that it is complete, and that the committed copy is current."""

from io import StringIO
from pathlib import Path
from typing import Any, get_args

from django.conf import settings
from django.core.management import call_command

import pytest
import yaml

from ..contract import API_BASE_PATH
from ..management.commands.export_openapi import (
    DEFAULT_OUTPUT,
    _merge,
    build_schema,
    render_schema,
)


@pytest.fixture(scope="module")
def schema() -> dict[str, Any]:
    return build_schema()


def test_the_committed_document_matches_the_routes() -> None:
    """The one test that keeps `openapi.yaml` from going stale.

    It is generated, not maintained, so a route or schema change that was not regenerated
    should fail here rather than ship a contract that describes the previous version.
    """
    committed = Path(settings.BASE_DIR) / DEFAULT_OUTPUT

    assert committed.exists(), f"{DEFAULT_OUTPUT} is missing. Run `manage.py export_openapi`."
    assert committed.read_text() == render_schema(), (
        f"{DEFAULT_OUTPUT} is out of date. Run `manage.py export_openapi` to regenerate it."
    )


def test_documents_every_route(schema: dict[str, Any]) -> None:
    assert set(schema["paths"]) == {
        f"{API_BASE_PATH}/capabilities",
        f"{API_BASE_PATH}/templates",
        f"{API_BASE_PATH}/templates/{{key}}",
        f"{API_BASE_PATH}/templates/{{key}}/versions",
        f"{API_BASE_PATH}/templates/{{key}}/versions/{{version}}",
        f"{API_BASE_PATH}/templates/{{key}}/composition",
        f"{API_BASE_PATH}/templates/{{key}}/status",
        f"{API_BASE_PATH}/templates/{{key}}/status-history",
        f"{API_BASE_PATH}/templates/{{key}}/activate",
        f"{API_BASE_PATH}/templates/{{key}}/deactivate",
        f"{API_BASE_PATH}/templates/{{key}}/archive",
        f"{API_BASE_PATH}/templates/{{key}}/preview",
        f"{API_BASE_PATH}/templates/{{key}}/tags",
        f"{API_BASE_PATH}/tags",
        f"{API_BASE_PATH}/tags/{{slug}}",
        f"{API_BASE_PATH}/tags/{{slug}}/archive",
        f"{API_BASE_PATH}/tags/{{slug}}/restore",
        "/health",
    }


def test_documents_the_unauthenticated_health_route(schema: dict[str, Any]) -> None:
    """`/health` lives on a second app, so it is only in the document because it is merged.

    Without the merge a client would code against a document that omits an endpoint the
    README documents, which is the failure this guards.
    """
    assert "security" not in schema["paths"]["/health"]["get"]


def test_every_api_route_requires_the_api_key(schema: dict[str, Any]) -> None:
    versioned = {
        path: operations
        for path, operations in schema["paths"].items()
        if path.startswith(API_BASE_PATH)
    }

    for path, operations in versioned.items():
        for method, operation in operations.items():
            assert operation.get("security"), f"{method.upper()} {path} declares no security"


def test_every_route_documents_the_error_envelope(schema: dict[str, Any]) -> None:
    """Clients branch on the error `code`, so every failure must be documented as carrying one."""
    for path, operations in schema["paths"].items():
        if not path.startswith(API_BASE_PATH):
            continue
        for method, operation in operations.items():
            # Ninja keys responses by int in the in-memory schema and by string once
            # serialized, so this reads the code rather than the key's type.
            failures = [code for code in operation["responses"] if not str(code).startswith("2")]
            assert failures, f"{method.upper()} {path} documents no error responses"
            for code in failures:
                schema_ref = operation["responses"][code]["content"]["application/json"]["schema"][
                    "$ref"
                ]
                assert schema_ref.endswith("ApiErrorResponse")


def test_the_document_is_valid_yaml_with_the_generated_header() -> None:
    rendered = render_schema()

    assert rendered.startswith("# Generated by `manage.py export_openapi`")
    assert yaml.safe_load(rendered)["openapi"].startswith("3.")


def test_the_status_enum_matches_the_library(schema: dict[str, Any]) -> None:
    """The wire spells statuses itself, so a status added to the library is a decision here."""
    from vintasend_managed_templates.constants import ManagedTemplateStatus

    documented = set(
        schema["components"]["schemas"]["SetStatusBody"]["properties"]["status"]["enum"]
    )

    assert documented == {status.value for status in ManagedTemplateStatus}


# --- the export command --------------------------------------------------------------
#
# CI runs `manage.py export_openapi --check` to catch a contract that was changed but not
# regenerated. That guard is only worth having if it actually fails, so it is tested in
# both directions rather than assumed.


def run_export(tmp_path: Path, *args: str) -> str:
    """Run the command against a throwaway output path, returning what it printed."""
    out = StringIO()
    call_command("export_openapi", "--output", str(tmp_path), *args, stdout=out, stderr=out)
    return out.getvalue()


def test_writes_the_document_to_the_requested_path(tmp_path: Path) -> None:
    target = tmp_path / "generated.yaml"

    output = run_export(target)

    assert target.read_text() == render_schema()
    assert "Wrote" in output


def test_check_passes_when_the_file_is_current(tmp_path: Path) -> None:
    target = tmp_path / "generated.yaml"
    target.write_text(render_schema())

    assert "up to date" in run_export(target, "--check")


def test_check_fails_when_the_file_is_stale(tmp_path: Path) -> None:
    """The failure direction: without this, the guard could be permanently green."""
    target = tmp_path / "generated.yaml"
    target.write_text(render_schema() + "\n# an edit that was never regenerated\n")

    with pytest.raises(SystemExit):
        run_export(target, "--check")


def test_check_fails_when_the_file_is_missing(tmp_path: Path) -> None:
    with pytest.raises(SystemExit):
        run_export(tmp_path / "does-not-exist.yaml", "--check")


def test_writes_to_stdout_when_asked(tmp_path: Path) -> None:
    out = StringIO()
    call_command("export_openapi", "--output", "-", stdout=out)

    assert out.getvalue().startswith("# Generated by `manage.py export_openapi`")


def test_a_name_the_two_apps_define_differently_is_refused() -> None:
    """The merge is narrow on purpose: a collision means the apps disagree about a name.

    Taking either silently would publish one app's shape under the other's name, so the
    generator refuses instead.
    """
    target = {"Shared": {"type": "object"}}

    with pytest.raises(RuntimeError, match="differently"):
        _merge(target, {"Shared": {"type": "string"}}, "schema")


def test_the_merge_accepts_an_identical_definition() -> None:
    target = {"Shared": {"type": "object"}}

    _merge(target, {"Shared": {"type": "object"}}, "schema")

    assert target == {"Shared": {"type": "object"}}


# --- the ordering vocabulary ---------------------------------------------------------
#
# The same six names live in three places: the enum in `openapi.yaml`, the literal this
# server validates against, and the library's own list of orderable fields. A field added to
# one and forgotten in the others is a client discovering it by getting a 400 from a
# parameter the spec says is valid, so it is pinned here instead.


def declared_enum(parameter_name: str) -> list[str]:
    """The enum a query parameter declares in the committed `openapi.yaml`.

    Read off the file on disk rather than the in-memory schema: the file is what a client
    generates from, and it is the copy shared with the TypeScript implementation.
    """
    document = yaml.safe_load((Path(settings.BASE_DIR) / DEFAULT_OUTPUT).read_text())
    operation = document["paths"][f"{API_BASE_PATH}/templates"]["get"]

    for parameter in operation["parameters"]:
        if parameter["name"] == parameter_name:
            for alternative in parameter["schema"]["anyOf"]:
                if "enum" in alternative:
                    return list(alternative["enum"])
            raise AssertionError(f"{parameter_name} declares no enum in {DEFAULT_OUTPUT}")

    raise AssertionError(f"{parameter_name} is not a parameter of GET /templates")


def test_the_spec_the_schema_and_the_library_name_the_same_orderable_fields() -> None:
    from vintasend_managed_templates.filters import MANAGED_TEMPLATE_ORDER_BY_FIELDS

    from ..contract import TemplateOrderByField
    from ..filters import ORDER_BY_FIELD_TO_PYTHON

    in_spec = sorted(declared_enum("orderByField"))
    in_schema = sorted(get_args(TemplateOrderByField))
    # The wire spells two of the six differently, so the library's list is compared through
    # the map that translates them -- which is itself a fourth place they could drift.
    in_library = sorted(ORDER_BY_FIELD_TO_PYTHON[wire] for wire in in_spec)

    assert in_spec == in_schema
    assert in_library == sorted(MANAGED_TEMPLATE_ORDER_BY_FIELDS)


def test_the_spec_and_the_schema_name_the_same_directions() -> None:
    from ..contract import TemplateOrderDirection

    assert sorted(declared_enum("orderByDirection")) == sorted(get_args(TemplateOrderDirection))


def test_a_capability_key_is_published_for_every_field_the_spec_accepts() -> None:
    """A field the API accepts but the report never mentions is one a client cannot discover.

    It would also fall to the ``False`` default and 400 on every request -- a limitation with
    nowhere to read it from.
    """
    from vintasend_managed_templates.filters import (
        DEFAULT_TEMPLATE_BACKEND_FILTER_CAPABILITIES,
        order_by_capability_key,
    )

    from ..filters import ORDER_BY_FIELD_TO_PYTHON

    for wire in declared_enum("orderByField"):
        key = order_by_capability_key(ORDER_BY_FIELD_TO_PYTHON[wire])
        assert key in DEFAULT_TEMPLATE_BACKEND_FILTER_CAPABILITIES


def test_the_drift_guard_fails_on_a_field_missing_from_the_spec(tmp_path: Path) -> None:
    """The guard above is only worth having if it fails, so the failure is exercised too.

    Rather than trusting that deleting a value from the enum by hand would be caught, this
    deletes one and asserts the same comparison rejects it.
    """
    from vintasend_managed_templates.filters import MANAGED_TEMPLATE_ORDER_BY_FIELDS

    from ..filters import ORDER_BY_FIELD_TO_PYTHON

    in_spec = sorted(field for field in declared_enum("orderByField") if field != "version")
    in_library = sorted(ORDER_BY_FIELD_TO_PYTHON[wire] for wire in in_spec)

    assert in_library != sorted(MANAGED_TEMPLATE_ORDER_BY_FIELDS)
