"""The generated contract: that it is complete, and that the committed copy is current."""

from pathlib import Path
from typing import Any

from django.conf import settings

import pytest
import yaml

from ..contract import API_BASE_PATH
from ..management.commands.export_openapi import DEFAULT_OUTPUT, build_schema, render_schema


@pytest.fixture(scope="module")
def schema() -> dict[str, Any]:
    return build_schema()


def test_the_committed_document_matches_the_routes() -> None:
    """The one test that keeps `openapi.yaml` from going stale.

    It is generated, not maintained, so a route or schema change that was not regenerated
    should fail here rather than ship a contract that describes the previous version.
    """
    committed = Path(settings.BASE_DIR) / DEFAULT_OUTPUT

    assert committed.exists(), f"{DEFAULT_OUTPUT} is missing. Run `manage.py export_openapi`."
    assert committed.read_text() == render_schema(), (
        f"{DEFAULT_OUTPUT} is out of date. Run `manage.py export_openapi` to regenerate it."
    )


def test_documents_every_route(schema: dict[str, Any]) -> None:
    assert set(schema["paths"]) == {
        f"{API_BASE_PATH}/capabilities",
        f"{API_BASE_PATH}/templates",
        f"{API_BASE_PATH}/templates/{{key}}",
        f"{API_BASE_PATH}/templates/{{key}}/versions",
        f"{API_BASE_PATH}/templates/{{key}}/versions/{{version}}",
        f"{API_BASE_PATH}/templates/{{key}}/composition",
        f"{API_BASE_PATH}/templates/{{key}}/status",
        f"{API_BASE_PATH}/templates/{{key}}/status-history",
        f"{API_BASE_PATH}/templates/{{key}}/activate",
        f"{API_BASE_PATH}/templates/{{key}}/deactivate",
        f"{API_BASE_PATH}/templates/{{key}}/archive",
        f"{API_BASE_PATH}/templates/{{key}}/preview",
        f"{API_BASE_PATH}/templates/{{key}}/tags",
        f"{API_BASE_PATH}/tags",
        f"{API_BASE_PATH}/tags/{{slug}}",
        f"{API_BASE_PATH}/tags/{{slug}}/archive",
        f"{API_BASE_PATH}/tags/{{slug}}/restore",
        "/health",
    }


def test_documents_the_unauthenticated_health_route(schema: dict[str, Any]) -> None:
    """`/health` lives on a second app, so it is only in the document because it is merged.

    Without the merge a client would code against a document that omits an endpoint the
    README documents, which is the failure this guards.
    """
    assert "security" not in schema["paths"]["/health"]["get"]


def test_every_api_route_requires_the_api_key(schema: dict[str, Any]) -> None:
    versioned = {
        path: operations
        for path, operations in schema["paths"].items()
        if path.startswith(API_BASE_PATH)
    }

    for path, operations in versioned.items():
        for method, operation in operations.items():
            assert operation.get("security"), f"{method.upper()} {path} declares no security"


def test_every_route_documents_the_error_envelope(schema: dict[str, Any]) -> None:
    """Clients branch on the error `code`, so every failure must be documented as carrying one."""
    for path, operations in schema["paths"].items():
        if not path.startswith(API_BASE_PATH):
            continue
        for method, operation in operations.items():
            # Ninja keys responses by int in the in-memory schema and by string once
            # serialized, so this reads the code rather than the key's type.
            failures = [code for code in operation["responses"] if not str(code).startswith("2")]
            assert failures, f"{method.upper()} {path} documents no error responses"
            for code in failures:
                schema_ref = operation["responses"][code]["content"]["application/json"]["schema"][
                    "$ref"
                ]
                assert schema_ref.endswith("ApiErrorResponse")


def test_the_document_is_valid_yaml_with_the_generated_header() -> None:
    rendered = render_schema()

    assert rendered.startswith("# Generated by `manage.py export_openapi`")
    assert yaml.safe_load(rendered)["openapi"].startswith("3.")


def test_the_status_enum_matches_the_library(schema: dict[str, Any]) -> None:
    """The wire spells statuses itself, so a status added to the library is a decision here."""
    from vintasend_managed_templates.constants import ManagedTemplateStatus

    documented = set(
        schema["components"]["schemas"]["SetStatusBody"]["properties"]["status"]["enum"]
    )

    assert documented == {status.value for status in ManagedTemplateStatus}
