"""Writes ``openapi.yaml`` from the live route table.

The schema is generated, never hand-maintained: ``contract.py`` and ``query.py`` are the
source, and this command is the only thing that produces the document. A test asserts the
committed file matches what this writes, so a route or schema change that is not
regenerated fails the suite rather than shipping a stale contract.
"""

import json
from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand, CommandParser

import yaml

from ...api import api, health_api


DEFAULT_OUTPUT = "openapi.yaml"

HEADER = (
    "# Generated by `manage.py export_openapi` -- do not edit by hand.\n"
    "# The source is the route declarations in\n"
    "# vintasend_templates_management_api/templates_manager/api.py and the schemas in contract.py\n"
    "# and query.py. Regenerate after changing any of them.\n"
)


class Command(BaseCommand):
    help = "Generate openapi.yaml from the API's route declarations."

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument(
            "--output",
            default=DEFAULT_OUTPUT,
            help=(
                f"Where to write the document, relative to the project root "
                f"(default: {DEFAULT_OUTPUT}). Pass '-' to write to stdout."
            ),
        )
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit non-zero if the file on disk differs, without writing it.",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        document = render_schema()

        if options["output"] == "-":
            self.stdout.write(document)
            return

        # The bundled project's BASE_DIR is the checkout, where the committed document
        # lives. A host project may not define one, so its working directory stands in.
        target = Path(getattr(settings, "BASE_DIR", None) or Path.cwd()) / options["output"]

        if options["check"]:
            current = target.read_text() if target.exists() else ""
            if current != document:
                self.stderr.write(
                    f"{target} is out of date. Run `manage.py export_openapi` to regenerate it."
                )
                raise SystemExit(1)
            self.stdout.write(f"{target} is up to date.")
            return

        target.write_text(document)
        self.stdout.write(f"Wrote {target}")


# `Any` throughout this module, deliberately. An OpenAPI document is a deeply nested,
# heterogeneous JSON tree that this code merges and indexes into by key; describing it as
# `JsonValue` would be accurate but would mean narrowing at every access, trading one
# `Any` for a dozen casts. `handle`'s signature is Django's, not ours.
def build_schema() -> dict[str, Any]:
    """The full contract as one OpenAPI document.

    ``/health`` lives on a second ``NinjaAPI`` -- it is unauthenticated and outside the
    versioned prefix, which is a different security scheme and so cannot share the main
    app's instance. It is still part of the contract a client codes against, so its single
    path and schema are merged in here rather than published as a separate document nobody
    would think to look for.

    The merge is one-directional and narrow on purpose: only ``paths`` and
    ``components.schemas`` are taken, and only for keys the main document does not already
    define. A collision would mean the two apps disagree about a name, which is worth
    failing on rather than resolving silently.
    """
    schema = api.get_openapi_schema()
    health = health_api.get_openapi_schema()

    _merge(schema.setdefault("paths", {}), health.get("paths", {}), "path")
    _merge(
        schema.setdefault("components", {}).setdefault("schemas", {}),
        health.get("components", {}).get("schemas", {}),
        "schema",
    )

    return schema


def _merge(target: dict[str, Any], extra: dict[str, Any], kind: str) -> None:
    for name, value in extra.items():
        if name in target and target[name] != value:
            raise RuntimeError(
                f"The health app defines {kind} {name!r} differently from the main app. "
                f"Rename one of them: the generated document can only carry one."
            )
        target[name] = value


def render_schema() -> str:
    """Serialize the generated schema to YAML, deterministically.

    Round-tripped through JSON first so pydantic's own types (``Url``, enums, and the like)
    become plain JSON values -- ``yaml.safe_dump`` would otherwise refuse them or, worse,
    tag them with a Python-specific type that no other tool reads.

    ``sort_keys=False`` preserves the order Ninja builds paths and schemas in, which keeps
    a regenerated document readable as a diff instead of a reshuffle.
    """
    schema = json.loads(json.dumps(build_schema()))
    body = yaml.safe_dump(schema, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return f"{HEADER}{body}"
